# Generated by Django 5.0.3 on 2024-04-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
